# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [4]:
x = np.array(range(20))
y = x * 2 - 1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [5]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [6]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 293ms/step - loss: 112.6502
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 112.3972
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 112.1444
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 111.8919
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 111.6398
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 111.3879
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 111.1364
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 110.8852
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 110.6343
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 110.3837


In [7]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [8]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 64ms/step


array([9.9960417e-03, 9.8914707e-01, 1.9682981e+00, 2.9474490e+00,
       3.9266000e+00, 4.9057508e+00, 5.8849020e+00, 6.8640532e+00,
       7.8432040e+00, 8.8223553e+00, 9.8015060e+00, 1.0780658e+01,
       1.1759809e+01, 1.2738959e+01, 1.3718111e+01, 1.4697262e+01,
       1.5676413e+01, 1.6655563e+01, 1.7634714e+01, 1.8613865e+01],
      dtype=float32)

## Now, Your turn!

In [27]:
import tensorflow as tf # 
from tensorflow import keras

import numpy as np

In [28]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [29]:
x.shape, y.shape

((20,), (20,))

In [30]:
# # 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
# keras.backend.clear_session()

# # 2번 모델 선언
# model = keras.models.Sequential()

# # 3번 모델 블록 조립
# model.add(keras.layers.Input(shape=(1,)))
# model.add(keras.layers.Dense(1))

# ## 오리지널 Sequential API
# # model.add( keras.layers.Dense(1, input_shape=(1,)) )

# # 4번 컴파일 
# model.compile(loss = 'mse',
#               optimizer = 'adam')

In [35]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam')

In [36]:
# epochs: 학습 회수
# verbose: 
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 326ms/step - loss: -247.0983
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: -247.3924
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: -247.6866
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: -247.9806
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: -248.2747
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: -248.5688
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: -248.8629
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: -249.1570
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: -249.4511
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: -249.7452


In [37]:
print(y)

[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [38]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 54ms/step


array([4.9750006e-01, 2.8554004e-01, 1.3892001e-01, 6.1143797e-02,
       2.5616247e-02, 1.0501056e-02, 4.2657284e-03, 1.7263604e-03,
       6.9760717e-04, 2.8172368e-04, 1.1374399e-04, 4.5918750e-05,
       1.8536768e-05, 7.4829172e-06, 3.0206825e-06, 1.2193769e-06,
       4.9223263e-07, 1.9870218e-07, 8.0211095e-08, 3.2379237e-08],
      dtype=float32)

## Quick Logistic Regression!

In [12]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [13]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [14]:
x.shape, y.shape
# ((20,), (20,)) = ((20, 1), (20, 1)) = Input(shape=(1,)), Dense(1, 'sigmoid')

((20,), (20,))

In [15]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
# binary_crossentropy: 확률분포 비교
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [16]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x))

Epoch 1/10
1/1 [==============================] - 0s 428ms/step - loss: 7.5801 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 7.5724 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 7.5647 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 7.5571 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 7.5494 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 7.5417 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 7.5341 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 7.5264 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 7.5187 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 7.5111 - accuracy: 0.4500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 

## Now, Your turn!

In [22]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [23]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [24]:
x.shape, y.shape

((40,), (40,))

In [25]:
# 모델링
# 이전 모델 클리어
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델에 레이어 설정
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

# 컴파일
model.compile(loss= 'binary_crossentropy', metrics=['accuracy'],
              optimizer = 'adam')

In [26]:
model.fit(x, y, epochs = 10, verbose= 1)

Epoch 1/10
2/2 [==============================] - 0s 7ms/step - loss: 6.6245 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 4ms/step - loss: 6.6140 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 4ms/step - loss: 6.6030 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 3ms/step - loss: 6.5934 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 3ms/step - loss: 6.5824 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 3ms/step - loss: 6.5734 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 4ms/step - loss: 6.5626 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 3ms/step - loss: 6.5531 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 6.5434 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 3ms/step - loss: 6.5330 - accuracy: 0.5250


In [7]:
print(y)
print(model.predict(x))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]
2/2 [==============================] - 0s 3ms/step
[[5.04917383e-01]
 [1.99886203e-01]
 [5.76665662e-02]
 [1.47688305e-02]
 [3.65851284e-03]
 [8.98657949e-04]
 [2.20281421e-04]
 [5.39682478e-05]
 [1.32204032e-05]
 [3.23845370e-06]
 [7.93280833e-07]
 [1.94319099e-07]
 [4.75997020e-08]
 [1.16598482e-08]
 [2.85614821e-09]
 [6.99631575e-10]
 [1.71379189e-10]
 [4.19804157e-11]
 [1.02833688e-11]
 [2.51897158e-12]
 [6.17037942e-13]
 [1.51147351e-13]
 [3.70244302e-14]
 [9.06936811e-15]
 [2.22159484e-15]
 [5.44192728e-16]
 [1.33303703e-16]
 [3.26535238e-17]
 [7.99867191e-18]
 [1.95932907e-18]
 [4.79949113e-19]
 [1.17566806e-19]
 [2.87986775e-20]
 [7.05440467e-21]
 [1.72802432e-21]
 [4.23289686e-22]
 [1.03687688e-22]
 [2.53989072e-23]
 [6.22161106e-24]
 [1.52402592e-24]]
