# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [48]:
from sklearn.datasets import load_iris

In [49]:
iris = load_iris()

In [50]:
x = iris.data
y = iris.target

In [51]:
x.shape, y.shape

((150, 4), (150,))

In [52]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow
from tensorflow import keras
from tensorflow.keras.utils import to_categorical

import numpy as np

from sklearn.model_selection import train_test_split

In [53]:
###############################
# train set / test set
# 조건 1. test set size = 10%
# 조건 2. 난수 고정 = 2023
###############################
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.1, random_state= 2023)

In [54]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((135, 4), (15, 4), (135,), (15,))

In [55]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [56]:
class_n = len(np.unique(y_train))
class_n

3

In [57]:
#######################
# 어떤 전처리 작업 필요: One-hot encoding
# Hint : y.shape
#######################
y_train = to_categorical(y_train, class_n)
y_test = to_categorical(y_test, class_n)

In [58]:
y_train.shape, y_test.shape

((135, 3), (15, 3))

In [59]:
########
# 모델링
########
# 1. 세션 종료
keras.backend.clear_session()

# 2. 모델 선언
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add(keras.layers.Input(4, ))
model.add(keras.layers.Dense(3, activation = 'softmax'))

# 4. 컴파일
model.compile(loss = 'categorical_crossentropy', metrics= ['accuracy'], optimizer= 'adam')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [60]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs = 10, verbose= 1)


Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 2.8160 - accuracy: 0.2370
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 2.7776 - accuracy: 0.2296
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 2.7367 - accuracy: 0.2296
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 2.6935 - accuracy: 0.2296
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 2.6525 - accuracy: 0.2074
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 2.6168 - accuracy: 0.2000
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 2.5799 - accuracy: 0.2000
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 2.5474 - accuracy: 0.2000
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 2.5169 - accuracy: 0.2148
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 2.4879 - accuracy: 0.2296


In [61]:
import pandas as pd

In [62]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)

1/1 [==============================] - 0s 40ms/step


In [63]:
# result = pd.DataFrame()
# result['y1', 'y2', 'y3'] = [y_test]
# result['y_pred'] = [y_pred]
# result
y_test


array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

# 히든 레이어 추가하여 모델링! (Functional API)
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [1]:
# 라이브러리 호출
import tensorflow
from tensorflow import keras
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np


In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
x = iris.data
y = iris.target

In [5]:
# 데이터 나누기
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 2023)

In [13]:
iris.feature_names, iris.target_names

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 array(['setosa', 'versicolor', 'virginica'], dtype='<U10'))

In [6]:
class_n = len(np.unique(y_train))

In [7]:
# 데이터 전처리
y_train = to_categorical(y_train, class_n)
y_test = to_categorical(y_test, class_n)

In [8]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((135, 4), (15, 4), (135, 3), (15, 3))

In [17]:
########
# 모델링: ANN
########
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 선언
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add(keras.layers.Input(shape = (4, )))
model.add(keras.layers.Dense(32, activation = 'relu'))
model.add(keras.layers.Dense(32, activation = 'relu'))
model.add(keras.layers.Dense(3, activation = 'softmax'))
          
# 4. 컴파일
# model.compile(loss = 'categorical_crossentropy', metrics= ['accuracy'], optimizer= 'adam')
model.compile(loss = keras.losses.categorical_crossentropy , metrics= ['accuracy'], optimizer= 'adam')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [18]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs = 10, verbose = 1)


Epoch 1/10
5/5 [==============================] - 1s 3ms/step - loss: 1.0703 - accuracy: 0.4815
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.9366 - accuracy: 0.8074
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8673 - accuracy: 0.6815
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.8244 - accuracy: 0.6815
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.7892 - accuracy: 0.6815
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.7555 - accuracy: 0.6815
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.7247 - accuracy: 0.6815
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.6991 - accuracy: 0.6815
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.6760 - accuracy: 0.8074
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.6513 - accuracy: 0.8519


In [19]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
print(y_test[:10])
print(y_pred[:10])


1/1 [==============================] - 0s 48ms/step
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0.06504924 0.4034277  0.5315231 ]
 [0.13526417 0.4368254  0.42791048]
 [0.14426158 0.423417   0.43232146]
 [0.04639943 0.4358772  0.5177233 ]
 [0.09139715 0.45033503 0.45826778]
 [0.08081187 0.39861435 0.52057385]
 [0.12822837 0.40543956 0.46633208]
 [0.1421431  0.421818   0.4360389 ]
 [0.7039543  0.17221944 0.1238262 ]
 [0.11288587 0.45410946 0.43300462]]
