# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(20)) 
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss='mse', optimizer='adam')

In [4]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 361ms/step - loss: 410.5454
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 410.0613
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 409.5775
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 409.0939
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 408.6106
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 408.1277
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 407.6451
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 407.1628
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 406.6808
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 406.1992


In [5]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 95ms/step
[0.00999793 0.12041702 0.23083611 0.3412552  0.45167428 0.5620933
 0.6725124  0.7829315  0.8933506  1.0037698  1.1141888  1.224608
 1.335027   1.4454461  1.5558652  1.6662843  1.7767034  1.8871224
 1.9975415  2.1079605 ]


## Now, Your turn!

In [7]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [9]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [12]:
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 레이어 사슬처럼 묶기
il = keras.layers.Input(shape = (1, ))
ol = keras.layers.Dense(1, activation = 'linear')(il)

# 3. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss= 'mse', optimizer = 'adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(y)
print(model.predict(x).reshape(-1,))

[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]
1/1 [==============================] - 0s 46ms/step
[  0.         -1.6498116  -3.2996233  -4.9494348  -6.5992465  -8.249058
  -9.8988695 -11.548681  -13.198493  -14.848305  -16.498116  -18.147928
 -19.797739  -21.447552  -23.097363  -24.747175  -26.396986  -28.046797
 -29.69661   -31.34642  ]


## Quick Logistic Regression!

In [14]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [15]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [16]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [17]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 0s 373ms/step - loss: 7.5238 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 7.5161 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 7.5084 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 7.5008 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 7.4931 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 7.4854 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 7.4778 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 7.4701 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 7.4624 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 7.4548 - accuracy: 0.4500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 

## Now, Your turn!

In [18]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [19]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [20]:
# 1. 세션클리어
keras.backend.clear_session()

# 2. 모델 사슬처럼 엮기
il = keras.layers.Input(shape = (1, ))
ol = keras.layers.Dense(1, activation = 'sigmoid')(il)

# 3. 모델 시작과 끝을 연결
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss = 'binary_crossentropy',
              metrics = ['accuracy'],
              optimizer = 'adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
2/2 [==============================] - 0s 6ms/step - loss: 6.2654 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 3ms/step - loss: 6.2558 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 2ms/step - loss: 6.2465 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 4ms/step - loss: 6.2366 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 4ms/step - loss: 6.2265 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 3ms/step - loss: 6.2173 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 4ms/step - loss: 6.2064 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 5ms/step - loss: 6.1961 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 5ms/step - loss: 6.1860 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 3ms/step - loss: 6.1760 - accuracy: 0.5250


In [22]:
print(y)
print(model.predict(x).reshape(-1,))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]
2/2 [==============================] - 0s 3ms/step
[0.4951363  0.78163946 0.9289022  0.9794604  0.9942874  0.99842834
 0.9995689  0.99988186 0.99996763 0.9999911  0.99999756 0.99999934
 0.9999998  0.9999999  1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.        ]
